version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=project
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        ports:
            - '3306:3306'

    nginx:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './resources/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '60000:80'

    php-fpm:
        build: resources/docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './resources/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    rabbitmq:
        build: resources/docker/rabbitmq
        ports:
            - 15672:15672
